// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'headerText': string;
  'listPageContainer': string;
  'listPageHeader': string;
  'listWrapper': string;
  'pokemonListItem': string;
}
export const cssExports: CssExports;
export default cssExports;
