// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'detailCard': string;
  'detailExit': string;
  'detailFeaturesContainer': string;
  'detailPageContainer': string;
  'detailTitleText': string;
  'detailValueText': string;
}
export const cssExports: CssExports;
export default cssExports;
